# Build-Umgebung für das Frontend
FROM node:14-alpine as frontend-build
WORKDIR /app
COPY ./spa/package*.json ./
RUN npm install
COPY ./spa/ ./
RUN npm run build

# production env
FROM nginx:stable-alpine
COPY --from=frontend-build /app/build /usr/share/nginx/html
# COPY ./spa/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]